version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: 0115a3a4-158d-4ef4-8d01-f0b277d175de
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  #mounts:
  #  - path: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/myconfig.xml
  #    value: |
  #      <server>
  #         <var name="io_openliberty_sample_system_inMaintenance" value="false"/>
  #      </server>
