version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: "5a80b1d9-a82a-452e-a0d7-3134c4a8a9ab"
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  #mounts:
  #  - path: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/myconfig.xml
  #    value: |
  #      <server>
  #         <var name="io_openliberty_sample_system_inMaintenance" value="false"/>
  #      </server>
